(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(elfeed-feeds
   '("http://ifeanyi.co/feed.xml" "http://byorgey.wordpress.com/feed/" "http://danluu.com/atom.xml" "http://www.bfilipek.com/feeds/posts/default" "https://lexi-lambda.github.io/feeds/all.atom.xml" "http://www.the-paper-trail.org/index.xml" "http://rachelbythebay.com/w/atom.xml" "https://matklad.github.io/feed.xml" "https://vorpus.org/blog/feeds/atom.xml" "http://thume.ca/atom.xml" "http://yunazuno.hatenablog.com/feed" "https://rushter.com/blog/feed/" "http://aturon.github.io/atom.xml" "http://this-week-in-rust.org/atom.xml" "http://antirez.com/rss" "https://blog.jessfraz.com/index.xml" "http://dave.cheney.net/feed" "https://fasterthanli.me/index.xml" "https://mpickering.github.io/atom.xml" "https://free.cofree.io/atom.xml" "https://jaspervdj.be/rss.xml" "http://blog.rust-lang.org/feed.xml" "https://www.python.org/dev/peps/peps.rss/" "https://blog.rust-lang.org/inside-rust/feed.xml" "http://feedpress.me/chosenplaintext" "https://www.youtube.com/feeds/videos.xml?channel_id=UCfbSz1B68ytEKX0D6AFdddQ" "https://xenaproject.wordpress.com/feed/" "http://graphicallinearalgebra.net/feed/" "http://centerofmathematics.blogspot.com/feeds/posts/default" "https://algorithmsandme.com/feed/" "https://www.youtube.com/feeds/videos.xml?channel_id=UCBLr7ISa_YDy5qeATupf26w" "https://rng-58.blogspot.com/feeds/posts/default" "http://feeds2.feedburner.com/PetrMitrichev" "http://blog.indeed.com/feed/" "https://www.nayuki.io/rss20.xml" "http://mindyourdecisions.com/blog/feed/" "http://emacsninja.com/feed.atom" "https://old.reddit.com/r/gwern/search.rss?q=flair:'Gwern'&sort=new&restrict_sr=on" "http://emacsredux.com/atom.xml" "https://buttondown.email/hillelwayne/rss" "https://www.joshwcomeau.com/rss.xml" "https://www.geoffreylitt.com/feed.xml" "http://www.allthingsdistributed.com/atom.xml" "http://blog.acolyer.org/feed/" "http://ericlippert.com/feed/" "https://www.rfc-editor.org/feed/" "https://thehikaku.net/rss20.xml" "http://blog.quarkslab.com/feeds/all.rss.xml" "https://microkerneldude.wordpress.com/feed/" "https://eng.uber.com/feed/" "http://fedoramagazine.org/feed/" "https://engineering.fb.com/feed/" "http://blog.cloudflare.com/rss/" "https://blog.packagecloud.io/feed.xml" "https://people.kernel.org/read/feed/" "https://vincent.bernat.ch/en/blog/atom.xml" "http://cumulusnetworks.com/blog/feed/" "https://github.blog/feed/" "https://www.fastly.com/blog_rss.xml" "http://feeds.feedburner.com/PackagecloudBlog" "https://haskell.libhunt.com/newsletter/feed" "https://python.libhunt.com/newsletter/feed" "https://rust.libhunt.com/newsletter/feed" "https://cpp.libhunt.com/newsletter/feed"))
 '(package-selected-packages '(package-lint)))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
